openapi: "3.0.0"
info:
  version: 1.0.0
  title: Contatos
  license:
    name: MIT
servers:
  - url: http://contatos.swagger.io/v1
paths:
  /contatos:
    get:
      summary: Listar todos os contatos
      operationId: listarContatos
      tags:
        - contatos
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Paginação
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Contato"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Criar Contato
      operationId: criarContato
      tags:
        - contatos
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /contatos/{contatoId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - contatos
      parameters:
        - name: contatoId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contatos"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Contato:
      required:
        - id
        - name
        - email
        - cel 
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        cel:
          type: string
    Contatos:
      type: array
      items:
        $ref: "#/components/schemas/Contato"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
